# 1. Docker basic image.
# For bozenka backend we will use python image (latest)
# 1. Base Image: Use an official Python runtime
FROM python:3.11-slim-buster 



#  2. Settings up enviroment for Python
ENV PYTHONDONTWRITEBYTECODE 1;
ENV PYTHONBUFFERED 1

# 3. Settings up work directory
WORKDIR /app

# 4. Update dependecies
RUN apt-get update 

# 5. Install python dependecies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 6. Copy code to our place
COPY . .

# 7. Start the server
# Expose the port for Django
EXPOSE 8000:8000

CMD ["python", "manage.py", "launch_bozenka"]