# Generated by Django 5.0.6 on 2024-07-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='icon',
            field=models.CharField(default='sell', max_length=50, verbose_name='Icon of Tag'),
        ),
    ]
