# Generated by Django 5.0.7 on 2024-07-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_tag_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='short_description',
            field=models.TextField(default='No short description provided', max_length=100, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(default='No description provided', verbose_name='Description'),
        ),
    ]
